### PR TITLE
Fix clone problem in WPK generation

### LINKED ISSUE #496: git clone in WPK generation does not work with tags
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 3.13.2-1 | WPK | Upgrade | Windows/Linuz |

Hello team,

We noticed that if a tag is specified as the branch in the WPK generation script then the tag will not be correctly cloned and master will be used to create the packages.

Regards,
Daniel Folch

### PR DESCRIPTION
**Pull request by DFolchA**
|Related issue|
|---|
|#496|

## Description
Hello team, 

This PR closes #496, we have replaced the `git clone` command with `curl`, this will avoid git related problems in the future.

## Tests

- Build the package in any supported platform
  - [x] Linux
  - [x] Windows
- [x] Package upgrade

### CODE REVIEW

File: wpk/run.sh [hunk 1]
```diff
@@ -133,7 +133,7 @@ main() {
 
     NO_COMPILE=false
     # Get Wazuh
-    git clone ${REPOSITORY} ${DIRECTORY} -b ${REFERENCE} --depth=1 || exit 1
+    curl -sL https://github.com/wazuh/wazuh/tarball/${REFERENCE} | tar zx
```
Comment (BraulioV) [inline wpk/run.sh:136]: You can remove the `.git` from the URL and use that variable with `curl`:
```suggestion
    curl -sL ${REPOSITORY}/tarball/${REFERENCE} | tar zx
```

**Review by BraulioV — CHANGES_REQUESTED** [review]

File: wpk/run.sh (hunk 1 above)
Comment (DFolchA) [reply wpk/run.sh]: Done in aade64a

**Review by BraulioV — APPROVED** [review]
