### PR TITLE
Fixed elasticsearch distributed installer

### LINKED ISSUE #1062: Fix the distributed version of the unified installer
|Unified unattended installer|

As seen on trying to make a distributed installation using https://github.com/wazuh/wazuh-packages/tree/unify-unattended, there are some bugs that need fixing.

- Missing `l` in  configureElasticsearch, `getConfig elasticsearch/roles/roles.ym`
- In `elasticsearch.sh`, line `copyCertificatesElasticsearch einame pos`
the arguments are passed without `${}` and aren't needed, the variables are accessed directly.
- Also in `elasticsearch.sh`, line `if [ ! ${IMN[@]} == ${einame}  ]; then`, the conditional doesn't work. It needs double brackets, [[ ]].
- In `kibana.sh`, the installation gets stuck on `until [[ "$(curl -XGET https://${kip}/status -I -uadmin:admin -k -s --max-time 300 | grep "200 OK")" ]]; do`. 
- After the elasticsearch installation, we can see this error in `/var/elasticsearch/wazuh.log`: `/etc/elasticsearch/certs/elasticsearch.pem has insecure file permissions (should be 0600)`
- After the filebeat installation, `filebeat test output` gives this error: `no such file or directory /etc/filebeat/certs/filebeat.pem`
- The initialization of Open Distro Security also fails: 
```
[root@centos7 unattended_scripts]# ls -l /etc/elasticsearch/certs/
total 20
-rw-r--r--. 1 root elasticsearch 1708 Dec 10 19:49 admin-key.pem
-rw-r--r--. 1 root elasticsearch 1103 Dec 10 19:49 admin.pem
-r--r--r--. 1 root elasticsearch 1704 Dec 10 19:49 elasticsearch-key.pem
-rw-r--r--. 1 root elasticsearch 1216 Dec 10 19:49 elasticsearch.pem
-rw-r--r--. 1 root elasticsearch 1180 Dec 10 19:49 root-ca.pem

[root@centos7 unattended_scripts]# /usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin.sh -cd ../securityconfig/ -nhnv -cacert /etc/elasticsearch/certs/root-ca.pem -cert /etc/elasticsearch/certs/admin.pem -key /etc/elasticsearch/certs/admin-key.pem -h 192.168.57.101
Open Distro Security Admin v7
Will connect to 192.168.57.101:9300 ... done
ERR: Cannot connect to Elasticsearch. Please refer to elasticsearch logfile for more information
Trace:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{bJdZCU8YQ-q0PoLakpSN-Q}{192.168.57.101}{192.168.57.101:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:352)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:248)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:57)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:391)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:412)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:401)
	at com.amazon.opendistroforelasticsearch.security.tools.OpenDistroSecurityAdmin.execute(OpenDistroSecurityAdmin.java:524)
	at com.amazon.opendistroforelasticsearch.security.tools.OpenDistroSecurityAdmin.main(OpenDistroSecurityAdmin.java:157)
```
- Errors when trying to start elasticsearch:
```
[root@centos7 unattended_scripts]# journalctl -r -u elasticsearch.service | grep -i -E "error|fatal|critical"
Dec 10 19:34:54 centos7 systemd-entrypoint[9360]: For complete error details, refer to the log at /var/log/elasticsearch/wazuh.log
Dec 10 19:33:32 centos7 systemd-entrypoint[8417]: For complete error details, refer to the log at /var/log/elasticsearch/wazuh.log
Dec 10 19:31:19 centos7 systemd-entrypoint[7470]: For complete error details, refer to the log at /var/log/elasticsearch/wazuh.log
Dec 10 19:29:55 centos7 systemd-entrypoint[6671]: For complete error details, refer to the log at /var/log/elasticsearch/wazuh.log
Dec 10 19:26:20 centos7 systemd-entrypoint[5729]: For complete error details, refer to the log at /var/log/elasticsearch/wazuh.log
Dec 10 19:25:08 centos7 systemd-entrypoint[4780]: For complete error details, refer to the log at /var/log/elasticsearch/wazuh.log
Dec 10 19:22:54 centos7 systemd-entrypoint[3810]: For complete error details, refer to the log at /var/log/elasticsearch/wazuh.log
Dec 10 19:22:54 centos7 systemd-entrypoint[3810]: at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
```

### PR DESCRIPTION
**Pull request by verdx**
|Related issue|
|---|
|closes #1062 |

## Description

I fixed a couple of bugs in the distributed elasticsearch installation. 
- Added a missing `l` for `getConfig roles.yml`
- Corrected missing brackets in condition
- Removed unused parameters in `copyCertificatesElasticsearch einame pos`

## Logs example
`filebeat test output`:
```
[root@centos7 unattended_scripts]# filebeat test output
elasticsearch: https://192.168.56.16:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 192.168.56.16
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... OK
  version: 7.10.2
```

## Tests
- [x] Two nodes, one with elasticsearch/kibana and another with Wazuh manager and filebeat. 
- [x] Four nodes, elasticsearch cluster

### CODE REVIEW

**Review by alberpilot — APPROVED** [review]
LGTM

File: unattended_scripts/install_functions/opendistro/elasticsearch.sh [hunk 1]
```diff
@@ -178,9 +178,9 @@ configureElasticsearch() {
     fi
 
     if [ -n "${single}" ]; then
-        copyCertificatesElasticsearch einame
+        copyCertificatesElasticsearch
     else
-        copyCertificatesElasticsearch einame pos
+        copyCertificatesElasticsearch
     fi
```
Comment (rauldpm) [inline unattended_scripts/install_functions/opendistro/elasticsearch.sh:184]: This will make the call whether it is fulfilled or not

File: unattended_scripts/install_functions/opendistro/kibana.sh [hunk 2]
```diff
@@ -96,6 +99,7 @@ copyKibanacerts() {
     if [ -d "${base_path}/certs" ]; then
         eval "cp ${base_path}/certs/kibana* /etc/kibana/certs/ ${debug}"
         eval "cp ${base_path}/certs/root-ca.pem /etc/kibana/certs/ ${debug}"
+
```
Comment (rauldpm) [inline unattended_scripts/install_functions/opendistro/kibana.sh:102]: This line is empty, remove it

**Review by rauldpm — CHANGES_REQUESTED** [review]
GJ, minor changes

File: unattended_scripts/install_functions/opendistro/elasticsearch.sh (hunk 1 above)
Comment (rauldpm) [reply unattended_scripts/install_functions/opendistro/elasticsearch.sh]: Done in https://github.com/wazuh/wazuh-packages/commit/39c0d9730785973b0736a4b86c2994b9917ac73d

File: unattended_scripts/install_functions/opendistro/kibana.sh (hunk 2 above)
Comment (rauldpm) [reply unattended_scripts/install_functions/opendistro/kibana.sh]: Done in https://github.com/wazuh/wazuh-packages/commit/39c0d9730785973b0736a4b86c2994b9917ac73d

**Review by alberpilot — APPROVED** [review]
LGTM
