### PR TITLE
Changed log message when not `yum` nor `apt-get` are found. Added clearer instructions on following steps.

### LINKED ISSUE #2444: Wazuh installation assistant - Unclear error when `yum` or `apt-get` are not found
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| v4.6.0-alpha1 | All-in-one | Quickstart installation | SUSE 15 |

As part of the [Wazuh v4.6.0-alpha1 E2E testing](https://github.com/wazuh/wazuh/issues/18823), I tried to install using Quickstart on SUSE 15, and I received the following error: "Couldn't find type of system."

This error message is not very descriptive. It should indicate that it couldn't find either the `yum` or `apt-get` package manager and include a link to the recommended operating systems.

```
function common_checkSystem() {

    if [ -n "$(command -v yum)" ]; then
        sys_type="yum"
        sep="-"
    elif [ -n "$(command -v apt-get)" ]; then
        sys_type="apt-get"
        sep="="
    else
        common_logger -e "Couldn't find type of system"
        exit 1
    fi
```
- Operating system details: 
```console
# cat /etc/os-release
NAME="SLES"
VERSION="15-SP5"
VERSION_ID="15.5"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp5"
DOCUMENTATION_URL="https://documentation.suse.com/"
```

- Quickstart installation error: 
```console
$ curl -sO https://packages-dev.wazuh.com/4.6/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
08/09/2023 14:39:04 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
08/09/2023 14:39:04 INFO: Verbose logging redirected to /var/log/wazuh-install.log
08/09/2023 14:39:04 ERROR: Couldn't find type of system
```

### PR DESCRIPTION
**Pull request by CarlosALgit**
|Related issue|
|---|
#2444
||

## Description

The previous log message was:
`ERROR: Couldn't find type of system`

This message has been changed to a more descriptive message:
`Couldn't find YUM or APT package manager. Try to install one of them with your current package manager. Then, launch the installation assistant again.`

## Log file
```
localhost:/home/vagrant/wazuh-packages # ./unattended_installer/wazuh-install.sh -a
22/04/2024 08:11:29 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
22/04/2024 08:11:29 INFO: Verbose logging redirected to /var/log/wazuh-install.log
22/04/2024 08:11:29 ERROR: Couldn't find YUM or APT package manager. Try installing the one corresponding to your operating system and then, launch the installation assistant again.
```

### CODE REVIEW

File: unattended_installer/common_functions/common.sh [hunk 1]
```diff
@@ -146,7 +146,7 @@ function common_checkSystem() {
         sep="="
         common_logger -d "APT package manager will be used."
     else
-        common_logger -e "Couldn't find type of system"
+        common_logger -e "Couldn't find YUM or APT package manager. Try to install one of them with your current package manager. Then, launch the installation assistant again."
```
Comment (teddytpc1) [inline unattended_installer/common_functions/common.sh:149]: I would use the following message:
`Couldn't find YUM or APT package manager. Try installing the one corresponding to your operating system and then, launch the installation assistant again.`

**Review by teddytpc1 — CHANGES_REQUESTED** [review]

**Review by davidcr01 — APPROVED** [review]

**Review by teddytpc1 — APPROVED** [review]

**Review by teddytpc1 — APPROVED** [review]
