### PR TITLE
Fix minor issues in OVA

### LINKED ISSUE #244: Elastic heap memory limits are badly set
Hi team,

After further testing, I found that the memory limits of Elasticsearch and Logstash are badly set. The reason is a typo in the sed lines where those limits are set:
- Elasticsearch: https://github.com/wazuh/wazuh-packages/blob/master/ova/Libraries/elastic_functions.sh#L57-L58
- Logstash: https://github.com/wazuh/wazuh-packages/blob/master/ova/Libraries/elastic_functions.sh#L207-L208

This may cause errors in both components if they don't have enough space to allocate their heaps.

### PR DESCRIPTION
**Pull request by DFolchA**
Hello team,

This PR closes #244 and #243 , in this PR I have that we detected with the ova.

I have tested the changes generating:
- [x] OVA 3.9.3-7.2.0 unstable
- [x] OVA 3.9.3-6.8.1 stable

Regards, 
Daniel Folch

### CODE REVIEW

File: ova/Libraries/wazuh_functions.sh [hunk 1]
```diff
@@ -66,7 +69,7 @@ delete_logs(){
     systemctl stop wazuh-manager
     systemctl stop wazuh-api
 
-    find ./ -type f \( -iname \*.log -o -iname \*.json \) -exec : > {} \;
+    find ${DIRECTORY}/logs -type f \( -iname \*.log -o -iname \*.json \) -exec truncate -s 0 `echo {}` \;
```
Comment (BraulioV) [inline ova/Libraries/wazuh_functions.sh]: This can be simplified if you remove the `echo` from it. ```truncate -s 0 `echo {}` ``` to ```truncate -s 0 {}```

Comment (DFolchA) [reply ova/Libraries/wazuh_functions.sh]: Done in https://github.com/wazuh/wazuh-packages/pull/246/commits/b572065aad0e2fe15af945fbc58eb3428fcc5528
