### PR TITLE
Fix AIX package generation script with chroot environment

### LINKED ISSUE #519: Fix AIX package generation error
Hello team,

We have detected some problem in our AIX environment that avoids correcting build 3.13.2/4.0.0 package.
The errors are related to the `/var` write permissions during package installation.

Regards.

### PR DESCRIPTION
**Pull request by okynos**
|Related issue|
|---|
| Closes #519 |

## Description

Hello team,

On this PR we have solved AIX package generation, to fix this we have added a `chroot` environment generation inside AIX host during the generation process.

Tasks:
- Added compilation of libssh2 inside `/usr/custom`.
- Added curl compilation with custom libssh2.
- Added chroot generation from base image directories, `/usr/pkg`.
- Added option to build or not `chroot` with `-ch`
- Review AIX SPECs.

Regards.

## Tests

- Build the package in any supported platform
  - [x] AIX

- Tests for IBM AIX
  - [x] `%files` section is correctly updated if necessary
  - [x] Check the changes from IBM AIX 5 (6 and 7 not checked).

### CODE REVIEW

File: aix/generate_wazuh_packages.sh [hunk 1]
```diff
@@ -32,16 +36,61 @@ show_help() {
...
-  echo "    -p, --install-path <rpm_home>       Installation path for the package. By default: /var"
-  echo "    -c, --checksum <path>               Compute the SHA512 checksum of the RPM package."
-  echo "    -h, --help                          Shows this help"
+  echo "    -b,  --branch <branch>               Select Git branch or tag. By default: ${reference}"
+  echo "    -r,  --revision <revision>           Define package revision text/number. By default: ${revision}"
+  echo "    -e,  --environment                   Install all the packages necessaries to build the RPM package"
+  echo "    -s,  --store  <rpm_directory>        Directory to store the resulting RPM package. By default: ${target_dir}"
+  echo "    -p,  --install-path <rpm_home>       Installation path for the package. By default: ${install_path}"
+  echo "    -c,  --checksum <path>               Compute the SHA512 checksum of the RPM package."
+  echo "    -ch, --chroot                        Build package inside chroot on ${chroot_path}"
```
Comment (BraulioV) [inline aix/generate_wazuh_packages.sh:45]:
```suggestion
  echo "   --chroot                        Create a chroot jail to build the package in ${chroot_path}."
```

File: aix/generate_wazuh_packages.sh [hunk 2]
```diff
@@ -283,6 +358,14 @@ main() {
                 shift 1
             fi
         ;;
+        "-ch" | "--chroot")
+            build_chroot="yes"
+            shift 1
+        ;;
```
Comment (BraulioV) [inline aix/generate_wazuh_packages.sh:364]:
```suggestion
        "--chroot")
          build_chroot="yes"
          shift 1
        ;;
```

**Review by BraulioV — CHANGES_REQUESTED** [review]

**Review by BraulioV — APPROVED** [review]
