### PR TITLE
Fixed HPUX checksum generation

### LINKED ISSUE #589: Fix HP-UX checksum parameter
Hi team,

The `generate_wazuh_packages.sh` script for HP-UX generates the checksum files with this format:
```
SHA512(wazuh-agent-4.1.0-1-hpux-11v3-ia64.tar)= a1365db32e104a2bec71fb92801476a45dcebbea05de4c85a3f4fcc52ea61df87ec05314d4614aba34965ea0ed81f61fad6a8054fd97e2d32b9f4a5c93130981  wazuh-agent-4.1.0-1-hpux-11v3-ia64.tar
```

meanwhile, the format must be this one:
```
a1365db32e104a2bec71fb92801476a45dcebbea05de4c85a3f4fcc52ea61df87ec05314d4614aba34965ea0ed81f61fad6a8054fd97e2d32b9f4a5c93130981  wazuh-agent-4.1.0-1-hpux-11v3-ia64.tar

### PR DESCRIPTION
**Pull request by BraulioV**
|Related issue|
|---|
|#589|

## Description

This PR closes #589 by fixing the checksum's file generation by parsing the output of the `openssl` command and unify it with the rest of the checksums' files generated by the scripts.
https://ci.wazuh.info/job/Packages_builder_special/146/console

## Logs example

```shellsession
# ./generate_wazuh_packages.sh -b v4.1.0-rc1 -c checksum
....
# cat wazuh-agent-4.1.0-1-hpux-11v3-ia64.tar.sha512
b554bfdd6294c5cf38c04987e7d8063d2577d6b317317f9cae975e295ba358205e70880accba245b921bf43880110094e34ad4dddad490ef8254812da8d9dbac  wazuh-agent-4.1.0-1-hpux-11v3-ia64.tar
```

## Tests

- Build the package in any supported platform
  - [x] HP-UX

### CODE REVIEW

**Review by alberpilot — APPROVED** [review]
LGTM

File: hp-ux/generate_wazuh_packages.sh [hunk 1]
```diff
@@ -139,7 +139,7 @@ create_package() {
 
   if [ "${compute_checksums}" = "yes" ]; then
     cd ${target_dir}
-    pkg_checksum="$(openssl dgst -sha512 ${pkg_name})"
+    pkg_checksum="$(openssl dgst -sha512 ${pkg_name} | cut -d'=' -f "2" | cut -b 2-)"
```
Comment (VictorMorenoJimenez) [inline hp-ux/generate_wazuh_packages.sh:142]: Just a suggestion:
`pkg_checksum="$(openssl dgst -sha512 ${pkg_name} | cut -d' ' -f "2")"`

**Review by VictorMorenoJimenez — APPROVED** [review]
Just a suggestion!

**Review by VictorMorenoJimenez — APPROVED** [review]
LGTM!
