### PR TITLE
Fix SSL error (date) and preremove script

### LINKED ISSUE #583: preremove script fails on legacy systems (solaris 10 sparc)
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.1.0 | Agent | Remove | Solaris 10 sparc |

This line is not accepted by the default `sh` shell on Solaris 10 (SPARC) .
```
wazuh_version=$(grep VERSION ${OSSEC_INIT} | sed 's/VERSION="v//g' | sed 's/"//g')
```

Proposed change:

```
#!/bin/sh
# preremove script for wazuh-agent

OSSEC_INIT="/etc/ossec-init.conf"
control_binary="wazuh-control"

. /etc/ossec-init.conf

set_control_binary() {
  number_version=`echo "${VERSION}" | cut -d v -f 2`
  major=`echo $number_version | cut -d . -f 1`
  minor=`echo $number_version | cut -d . -f 2`

  if [ "$major" -le "4" ] && [ "$minor" -le "1" ]; then
    control_binary="ossec-control"
  fi
}

set_control_binary

/var/ossec/bin/${control_binary} stop
```

Another option may be to replace the `$()` by legacy quotation  syntax

```
wazuh_version=`grep VERSION ${OSSEC_INIT} | sed 's/VERSION="v//g' | sed 's/"//g'`
```

### PR DESCRIPTION
**Pull request by okynos**
|Related issue|
|---|
| Closes #583 |

## Description

Hello team,

We have added a fix on Solaris 10 preremove script that left some files inside the installation path.

## Tests

- Build the package in any supported platform
  - [x] Solaris
- [x] Package installation
- [x] Package upgrade
- [x] Package remove

- Tests for Solaris
  - [x] Test the package on Solaris 10

Regards!

### CODE REVIEW

File: solaris/solaris10/preremove.sh [hunk 1]
```diff
@@ -4,9 +4,10 @@
 OSSEC_INIT="/etc/ossec-init.conf"
 control_binary="wazuh-control"
 
+. /etc/ossec-init.conf
```
Comment (BraulioV) [inline solaris/solaris10/preremove.sh:7]:
```suggestion
. ${OSSEC_INIT}
```

**Review by BraulioV — CHANGES_REQUESTED** [review]

**Review by BraulioV — APPROVED** [review]
